name = "kilterboardie-api"
main = "index.js"
compatibility_date = "2024-11-01"

[vars]
PUBLIC_REPO_OWNER = "Pa-Sto"
PUBLIC_REPO_NAME = "kilterboardie"
DATA_REPO_OWNER = "Pa-Sto"
DATA_REPO_NAME = "kilterboardie-feedback"
DATA_REPO_BRANCH = "main"
PUBLIC_SITE_BASE = "https://raw.githubusercontent.com/Pa-Sto/kilterboardie/generated"
